export const INITIAL_TIME = 30; // seconds
export const PENALTY_SECONDS = 3;
export const CHOICE_COUNT = 2;
export const GOLD_STRAWBERRY_CHANCE = 0.03; // 3% chance for cake (about 1 in 33)
export const GOLD_STRAWBERRY_POINTS = 3;
export const GOLD_STRAWBERRY_TIME_BONUS = 20; // 2 seconds in 0.1 second units
export const WHOLE_CAKE_CHANCE = 0.01; // 1% chance for whole cake (about 1 in 100)
export const WHOLE_CAKE_POINTS = 5;
export const WHOLE_CAKE_TIME_BONUS = 50; // 5 seconds in 0.1 second units
export const MEMORY_GAME_CHANCE = 1.0; // 100% chance for memory game
export const DISTRACTOR_EMOJIS = ['🍎', '🍊', '🍇', '🍉', '🍍', '🍑', '🥝', '🫐', '🍒', '🍈'];

// Island game constants
export const ISLAND_NAMES = [
  { id: '1_hokkaido_rebuntou', name: '礼文島', file: '1_hokkaido_rebuntou.svg', prefecture: '北海道' },
  { id: '2_hokkaido_rishiritou', name: '利尻島', file: '2_hokkaido_rishiritou.svg', prefecture: '北海道' },
  { id: '3_hokkaido_yagishiritou', name: '焼尻島', file: '3_hokkaido_yagishiritou.svg', prefecture: '北海道' },
  { id: '4_hokkaido_teuritou', name: '天売島', file: '4_hokkaido_teuritou.svg', prefecture: '北海道' },
  { id: '5_hokkaido_okushiritou', name: '奥尻島', file: '5_hokkaido_okushiritou.svg', prefecture: '北海道' },
  { id: '6_hokkaido_kojima', name: '小島', file: '6_hokkaido_kojima.svg', prefecture: '北海道' },
  { id: '7_miyagi_oshima', name: '大島', file: '7_miyagi_oshima.svg', prefecture: '宮城県' },
  { id: '8_miyagi_izushima', name: '出島', file: '8_miyagi_izushima.svg', prefecture: '宮城県' },
  { id: '9_miyagi_enoshima', name: '江島', file: '9_miyagi_enoshima.svg', prefecture: '宮城県' },
  { id: '10_miyagi_ajishima', name: '網地島', file: '10_miyagi_ajishima.svg', prefecture: '宮城県' },
  { id: '11_miyagi_tashirojima', name: '田代島', file: '11_miyagi_tashirojima.svg', prefecture: '宮城県' },
  { id: '12_miyagi_kinkasan', name: '金華山', file: '12_miyagi_kinkasan.svg', prefecture: '宮城県' },
  { id: '13_miyagi_sabusawajima', name: '寒風沢島', file: '13_miyagi_sabusawajima.svg', prefecture: '宮城県' },
  { id: '14_miyagi_nonoshima', name: '野々島', file: '14_miyagi_nonoshima.svg', prefecture: '宮城県' },
  { id: '15_miyagi_katsurajima', name: '桂島', file: '15_miyagi_katsurajima.svg', prefecture: '宮城県' },
  { id: '16_miyagi_hoojima', name: '朴島', file: '16_miyagi_hoojima.svg', prefecture: '宮城県' },
  { id: '17_miyagi_miyatojima', name: '宮戸島', file: '17_miyagi_miyatojima.svg', prefecture: '宮城県' },
  { id: '18_yamagata_tobishima', name: '飛島', file: '18_yamagata_tobishima.svg', prefecture: '山形県' },
  { id: '19_chiba_niemonjima', name: '仁右衛門島', file: '19_chiba_niemonjima.svg', prefecture: '千葉県' },
  { id: '20_tokyo_oshima', name: '大島', file: '20_tokyo_oshima.svg', prefecture: '東京都' },
  { id: '21_tokyo_toshima', name: '利島', file: '21_tokyo_toshima.svg', prefecture: '東京都' },
  { id: '22_tokyo_nijima', name: '新島', file: '22_tokyo_nijima.svg', prefecture: '東京都' },
  { id: '23_tokyo_shikinejima', name: '式根島', file: '23_tokyo_shikinejima.svg', prefecture: '東京都' },
  { id: '24_tokyo_kozushima', name: '神津島', file: '24_tokyo_kozushima.svg', prefecture: '東京都' },
  { id: '25_tokyo_miyakejima', name: '三宅島', file: '25_tokyo_miyakejima.svg', prefecture: '東京都' },
  { id: '26_tokyo_mikurajima', name: '御蔵島', file: '26_tokyo_mikurajima.svg', prefecture: '東京都' },
  { id: '27_tokyo_hachijoshima', name: '八丈島', file: '27_tokyo_hachijoshima.svg', prefecture: '東京都' },
  { id: '28_tokyo_aogashima', name: '青ヶ島', file: '28_tokyo_aogashima.svg', prefecture: '東京都' },
  { id: '29_tokyo_chichijima', name: '父島', file: '29_tokyo_chichijima.svg', prefecture: '東京都' },
  { id: '30_tokyo_hahajima', name: '母島', file: '30_tokyo_hahajima.svg', prefecture: '東京都' },
  { id: '31_tokyo_ioujima', name: '硫黄島', file: '31_tokyo_ioujima.svg', prefecture: '東京都' },
  { id: '32_tokyo_minamitorishima', name: '南鳥島', file: '32_tokyo_minamitorishima.svg', prefecture: '東京都' },
  { id: '33_kanagawa_jogashima', name: '城ヶ島', file: '33_kanagawa_jogashima.svg', prefecture: '神奈川県' },
  { id: '34_kanagawa_enoshima', name: '江の島', file: '34_kanagawa_enoshima.svg', prefecture: '神奈川県' },
  { id: '40_shizuoka_hatsushima', name: '初島', file: '40_shizuoka_hatsushima.svg', prefecture: '静岡県' }
];

// Flag game constants
export const COUNTRIES = [
  // アジア
  { id: 'japan', name: '日本', code: 'jp' },
  { id: 'china', name: '中国', code: 'cn' },
  { id: 'korea', name: '韓国', code: 'kr' },
  { id: 'thailand', name: 'タイ', code: 'th' },
  { id: 'singapore', name: 'シンガポール', code: 'sg' },
  { id: 'malaysia', name: 'マレーシア', code: 'my' },
  { id: 'indonesia', name: 'インドネシア', code: 'id' },
  { id: 'philippines', name: 'フィリピン', code: 'ph' },
  { id: 'vietnam', name: 'ベトナム', code: 'vn' },
  { id: 'india', name: 'インド', code: 'in' },
  { id: 'pakistan', name: 'パキスタン', code: 'pk' },
  { id: 'bangladesh', name: 'バングラデシュ', code: 'bd' },
  { id: 'sri-lanka', name: 'スリランカ', code: 'lk' },
  { id: 'myanmar', name: 'ミャンマー', code: 'mm' },
  { id: 'cambodia', name: 'カンボジア', code: 'kh' },
  { id: 'laos', name: 'ラオス', code: 'la' },
  { id: 'brunei', name: 'ブルネイ', code: 'bn' },
  { id: 'mongolia', name: 'モンゴル', code: 'mn' },
  { id: 'north-korea', name: '北朝鮮', code: 'kp' },
  { id: 'taiwan', name: '台湾', code: 'tw' },
  { id: 'hong-kong', name: '香港', code: 'hk' },
  { id: 'macau', name: 'マカオ', code: 'mo' },
  { id: 'nepal', name: 'ネパール', code: 'np' },
  { id: 'bhutan', name: 'ブータン', code: 'bt' },
  { id: 'maldives', name: 'モルディブ', code: 'mv' },
  { id: 'afghanistan', name: 'アフガニスタン', code: 'af' },
  { id: 'uzbekistan', name: 'ウズベキスタン', code: 'uz' },
  { id: 'kazakhstan', name: 'カザフスタン', code: 'kz' },
  { id: 'kyrgyzstan', name: 'キルギス', code: 'kg' },
  { id: 'tajikistan', name: 'タジキスタン', code: 'tj' },
  { id: 'turkmenistan', name: 'トルクメニスタン', code: 'tm' },
  
  // ヨーロッパ
  { id: 'uk', name: 'イギリス', code: 'gb' },
  { id: 'france', name: 'フランス', code: 'fr' },
  { id: 'germany', name: 'ドイツ', code: 'de' },
  { id: 'italy', name: 'イタリア', code: 'it' },
  { id: 'spain', name: 'スペイン', code: 'es' },
  { id: 'netherlands', name: 'オランダ', code: 'nl' },
  { id: 'belgium', name: 'ベルギー', code: 'be' },
  { id: 'switzerland', name: 'スイス', code: 'ch' },
  { id: 'austria', name: 'オーストリア', code: 'at' },
  { id: 'sweden', name: 'スウェーデン', code: 'se' },
  { id: 'norway', name: 'ノルウェー', code: 'no' },
  { id: 'denmark', name: 'デンマーク', code: 'dk' },
  { id: 'finland', name: 'フィンランド', code: 'fi' },
  { id: 'iceland', name: 'アイスランド', code: 'is' },
  { id: 'ireland', name: 'アイルランド', code: 'ie' },
  { id: 'portugal', name: 'ポルトガル', code: 'pt' },
  { id: 'greece', name: 'ギリシャ', code: 'gr' },
  { id: 'poland', name: 'ポーランド', code: 'pl' },
  { id: 'czech', name: 'チェコ', code: 'cz' },
  { id: 'slovakia', name: 'スロバキア', code: 'sk' },
  { id: 'hungary', name: 'ハンガリー', code: 'hu' },
  { id: 'romania', name: 'ルーマニア', code: 'ro' },
  { id: 'bulgaria', name: 'ブルガリア', code: 'bg' },
  { id: 'croatia', name: 'クロアチア', code: 'hr' },
  { id: 'serbia', name: 'セルビア', code: 'rs' },
  { id: 'bosnia', name: 'ボスニア・ヘルツェゴビナ', code: 'ba' },
  { id: 'montenegro', name: 'モンテネグロ', code: 'me' },
  { id: 'albania', name: 'アルバニア', code: 'al' },
  { id: 'north-macedonia', name: '北マケドニア', code: 'mk' },
  { id: 'slovenia', name: 'スロベニア', code: 'si' },
  { id: 'estonia', name: 'エストニア', code: 'ee' },
  { id: 'latvia', name: 'ラトビア', code: 'lv' },
  { id: 'lithuania', name: 'リトアニア', code: 'lt' },
  { id: 'belarus', name: 'ベラルーシ', code: 'by' },
  { id: 'ukraine', name: 'ウクライナ', code: 'ua' },
  { id: 'moldova', name: 'モルドバ', code: 'md' },
  { id: 'russia', name: 'ロシア', code: 'ru' },
  { id: 'georgia', name: 'ジョージア', code: 'ge' },
  { id: 'armenia', name: 'アルメニア', code: 'am' },
  { id: 'azerbaijan', name: 'アゼルバイジャン', code: 'az' },
  { id: 'turkey', name: 'トルコ', code: 'tr' },
  { id: 'cyprus', name: 'キプロス', code: 'cy' },
  { id: 'malta', name: 'マルタ', code: 'mt' },
  { id: 'luxembourg', name: 'ルクセンブルク', code: 'lu' },
  { id: 'monaco', name: 'モナコ', code: 'mc' },
  { id: 'andorra', name: 'アンドラ', code: 'ad' },
  { id: 'san-marino', name: 'サンマリノ', code: 'sm' },
  { id: 'vatican', name: 'バチカン', code: 'va' },
  { id: 'liechtenstein', name: 'リヒテンシュタイン', code: 'li' },
  
  // 北アメリカ
  { id: 'usa', name: 'アメリカ', code: 'us' },
  { id: 'canada', name: 'カナダ', code: 'ca' },
  { id: 'mexico', name: 'メキシコ', code: 'mx' },
  { id: 'guatemala', name: 'グアテマラ', code: 'gt' },
  { id: 'belize', name: 'ベリーズ', code: 'bz' },
  { id: 'el-salvador', name: 'エルサルバドル', code: 'sv' },
  { id: 'honduras', name: 'ホンジュラス', code: 'hn' },
  { id: 'nicaragua', name: 'ニカラグア', code: 'ni' },
  { id: 'costa-rica', name: 'コスタリカ', code: 'cr' },
  { id: 'panama', name: 'パナマ', code: 'pa' },
  { id: 'cuba', name: 'キューバ', code: 'cu' },
  { id: 'jamaica', name: 'ジャマイカ', code: 'jm' },
  { id: 'haiti', name: 'ハイチ', code: 'ht' },
  { id: 'dominican-republic', name: 'ドミニカ共和国', code: 'do' },
  { id: 'bahamas', name: 'バハマ', code: 'bs' },
  { id: 'barbados', name: 'バルバドス', code: 'bb' },
  { id: 'trinidad-tobago', name: 'トリニダード・トバゴ', code: 'tt' },
  
  // 南アメリカ
  { id: 'brazil', name: 'ブラジル', code: 'br' },
  { id: 'argentina', name: 'アルゼンチン', code: 'ar' },
  { id: 'chile', name: 'チリ', code: 'cl' },
  { id: 'peru', name: 'ペルー', code: 'pe' },
  { id: 'colombia', name: 'コロンビア', code: 'co' },
  { id: 'venezuela', name: 'ベネズエラ', code: 've' },
  { id: 'ecuador', name: 'エクアドル', code: 'ec' },
  { id: 'bolivia', name: 'ボリビア', code: 'bo' },
  { id: 'paraguay', name: 'パラグアイ', code: 'py' },
  { id: 'uruguay', name: 'ウルグアイ', code: 'uy' },
  { id: 'guyana', name: 'ガイアナ', code: 'gy' },
  { id: 'suriname', name: 'スリナム', code: 'sr' },
  
  // アフリカ
  { id: 'south-africa', name: '南アフリカ', code: 'za' },
  { id: 'egypt', name: 'エジプト', code: 'eg' },
  { id: 'nigeria', name: 'ナイジェリア', code: 'ng' },
  { id: 'kenya', name: 'ケニア', code: 'ke' },
  { id: 'ethiopia', name: 'エチオピア', code: 'et' },
  { id: 'ghana', name: 'ガーナ', code: 'gh' },
  { id: 'morocco', name: 'モロッコ', code: 'ma' },
  { id: 'algeria', name: 'アルジェリア', code: 'dz' },
  { id: 'tunisia', name: 'チュニジア', code: 'tn' },
  { id: 'libya', name: 'リビア', code: 'ly' },
  { id: 'sudan', name: 'スーダン', code: 'sd' },
  { id: 'uganda', name: 'ウガンダ', code: 'ug' },
  { id: 'tanzania', name: 'タンザニア', code: 'tz' },
  { id: 'zambia', name: 'ザンビア', code: 'zm' },
  { id: 'zimbabwe', name: 'ジンバブエ', code: 'zw' },
  { id: 'botswana', name: 'ボツワナ', code: 'bw' },
  { id: 'namibia', name: 'ナミビア', code: 'na' },
  { id: 'angola', name: 'アンゴラ', code: 'ao' },
  { id: 'mozambique', name: 'モザンビーク', code: 'mz' },
  { id: 'madagascar', name: 'マダガスカル', code: 'mg' },
  { id: 'mauritius', name: 'モーリシャス', code: 'mu' },
  { id: 'senegal', name: 'セネガル', code: 'sn' },
  { id: 'ivory-coast', name: 'コートジボワール', code: 'ci' },
  { id: 'mali', name: 'マリ', code: 'ml' },
  { id: 'burkina-faso', name: 'ブルキナファソ', code: 'bf' },
  { id: 'niger', name: 'ニジェール', code: 'ne' },
  { id: 'chad', name: 'チャド', code: 'td' },
  { id: 'cameroon', name: 'カメルーン', code: 'cm' },
  { id: 'gabon', name: 'ガボン', code: 'ga' },
  { id: 'congo', name: 'コンゴ共和国', code: 'cg' },
  { id: 'drc', name: 'コンゴ民主共和国', code: 'cd' },
  { id: 'rwanda', name: 'ルワンダ', code: 'rw' },
  { id: 'burundi', name: 'ブルンジ', code: 'bi' },
  
  // オセアニア
  { id: 'australia', name: 'オーストラリア', code: 'au' },
  { id: 'new-zealand', name: 'ニュージーランド', code: 'nz' },
  { id: 'fiji', name: 'フィジー', code: 'fj' },
  { id: 'papua-new-guinea', name: 'パプアニューギニア', code: 'pg' },
  { id: 'samoa', name: 'サモア', code: 'ws' },
  { id: 'tonga', name: 'トンガ', code: 'to' },
  { id: 'vanuatu', name: 'バヌアツ', code: 'vu' },
  { id: 'solomon-islands', name: 'ソロモン諸島', code: 'sb' },
  { id: 'palau', name: 'パラオ', code: 'pw' },
  { id: 'micronesia', name: 'ミクロネシア', code: 'fm' },
  { id: 'marshall-islands', name: 'マーシャル諸島', code: 'mh' },
  { id: 'kiribati', name: 'キリバス', code: 'ki' },
  { id: 'tuvalu', name: 'ツバル', code: 'tv' },
  { id: 'nauru', name: 'ナウル', code: 'nr' },
  
  // 中東
  { id: 'saudi-arabia', name: 'サウジアラビア', code: 'sa' },
  { id: 'uae', name: 'アラブ首長国連邦', code: 'ae' },
  { id: 'qatar', name: 'カタール', code: 'qa' },
  { id: 'kuwait', name: 'クウェート', code: 'kw' },
  { id: 'bahrain', name: 'バーレーン', code: 'bh' },
  { id: 'oman', name: 'オマーン', code: 'om' },
  { id: 'yemen', name: 'イエメン', code: 'ye' },
  { id: 'iraq', name: 'イラク', code: 'iq' },
  { id: 'iran', name: 'イラン', code: 'ir' },
  { id: 'syria', name: 'シリア', code: 'sy' },
  { id: 'lebanon', name: 'レバノン', code: 'lb' },
  { id: 'jordan', name: 'ヨルダン', code: 'jo' },
  { id: 'israel', name: 'イスラエル', code: 'il' },
  { id: 'palestine', name: 'パレスチナ', code: 'ps' }
];

const FLAG_GAME_TYPE = 'flag_rush';
const SQUARE_GAME_TYPE = 'square_rush';
const CUBE_GAME_TYPE = 'cube_rush';
const RANKING_LIMIT = 30;

// Color game constants - 色彩検定127色
export const COLORS = [
  // 赤系
  { id: '1', name: 'あか (赤)', nameEn: 'Red', munsell: '5R 4/14', hex: '#EE0000', description: '暖色を代表する、最も彩度の高い赤。炎、血液の色。' },
  { id: '2', name: 'クリムソン', nameEn: 'Crimson', munsell: '10R 3/10', hex: '#A30026', description: '紫みを帯びた暗い赤。深紅に近い、濃く落ち着いた赤。' },
  { id: '3', name: 'えんじ (臙脂)', nameEn: 'Dark Red', munsell: '7.5R 3/8', hex: '#8C2727', description: '黒みがかった濃い赤。絹織物などに使われる伝統色。' },
  { id: '4', name: 'カーディナルレッド', nameEn: 'Cardinal Red', munsell: '7.5R 4/10', hex: '#B4103B', description: '枢機卿（カーディナル）の法衣の色に由来する、鮮やかな赤。' },
  { id: '5', name: 'マホガニー', nameEn: 'Mahogany', munsell: '5R 3/4', hex: '#652E2E', description: 'マホガニー材のような、暗い赤みの茶色。' },
  { id: '6', name: 'ワインレッド', nameEn: 'Wine Red', munsell: '7.5R 3/6', hex: '#7C283C', description: '熟成した赤ワインのような、深みのある暗赤色。' },
  { id: '7', name: 'べにいろ (紅)', nameEn: 'Crimson', munsell: '10R 4/14', hex: '#D00045', description: '紅花で染めた濃い赤。伝統的な鮮やかな赤。' },
  { id: '8', name: 'ローズレッド', nameEn: 'Rose Red', munsell: '5R 5/12', hex: '#E73151', description: 'バラの花のような、あざやかな赤。' },
  { id: '9', name: 'コーラル', nameEn: 'Coral', munsell: '2.5YR 7/10', hex: '#FF886F', description: '珊瑚のような、明るい黄みの赤。' },
  { id: '10', name: 'スカーレット', nameEn: 'Scarlet', munsell: '5R 5.5/14', hex: '#E3001F', description: '炎のような、輝くようなあざやかな赤。' },
  { id: '11', name: 'バーミリオン', nameEn: 'Vermilion', munsell: '7.5R 5/14', hex: '#F15A22', description: '鮮やかな黄みの赤。朱肉や神社仏閣に用いられる朱色。' },
  { id: '12', name: 'さんごいろ (珊瑚色)', nameEn: 'Coral', munsell: '2.5YR 7/10', hex: '#FF886F', description: '海のサンゴのような、黄みを帯びた明るい赤。' },
  { id: '13', name: 'サーモンピンク', nameEn: 'Salmon Pink', munsell: '5R 7/6', hex: '#F9A3A8', description: '鮭の肉の色のような、淡い黄みの赤。' },
  { id: '14', name: 'ときいろ (鴇色)', nameEn: 'Salmon Pink', munsell: '7.5R 8/4', hex: '#F7C4C2', description: 'トキの羽のような、ごく淡い上品なピンク。' },
  { id: '15', name: 'ピンク', nameEn: 'Pink', munsell: '5RP 7/8', hex: '#FF7E7E', description: '桜の花のような、明るい赤。かわいらしい印象。' },
  { id: '16', name: 'ショッキングピンク', nameEn: 'Shocking Pink', munsell: '5RP 5/14', hex: '#FF009A', description: '強く刺激的な、非常に鮮やかな赤紫。' },
  { id: '17', name: 'カーネーション', nameEn: 'Carnation', munsell: '10RP 6/10', hex: '#FF66B3', description: 'カーネーションの花のような、鮮やかな赤紫。' },
  { id: '18', name: 'チェリーピンク', nameEn: 'Cherry Pink', munsell: '5RP 6/10', hex: '#FF3399', description: 'さくらんぼのような、あざやかな赤紫。' },
  { id: '19', name: 'ローズ', nameEn: 'Rose', munsell: '10RP 6/10', hex: '#FF3399', description: 'バラのような、あざやかな赤紫。' },
  { id: '20', name: 'マゼンタ', nameEn: 'Magenta', munsell: '5RP 5/12', hex: '#FF0090', description: '印刷の三原色の一つ。鮮烈な赤紫。' },
  // 黄赤系
  { id: '21', name: 'だいだい (橙)', nameEn: 'Orange', munsell: '5YR 6.5/14', hex: '#FF8000', description: '赤と黄の中間の色。果物のオレンジのような活発な色。' },
  { id: '22', name: 'オレンジ', nameEn: 'Orange', munsell: '5YR 6.5/14', hex: '#FF8000', description: '大大と同義。フレッシュで暖かい印象。' },
  { id: '23', name: 'カッパー', nameEn: 'Copper', munsell: '5YR 4/8', hex: '#B85526', description: '銅のような、光沢のある赤みの茶色。' },
  { id: '24', name: 'テラコッタ', nameEn: 'Terracotta', munsell: '5YR 5/6', hex: '#AD5947', description: '素焼きの焼き物のような、赤みがかった茶色。' },
  { id: '25', name: 'アプリコット', nameEn: 'Apricot', munsell: '5YR 7/8', hex: '#FFC192', description: '杏（アプリコット）の実のような、明るい黄みの赤。' },
  { id: '26', name: 'タン', nameEn: 'Tan', munsell: '7.5YR 5/6', hex: '#A56E42', description: 'なめし皮のような、茶色がかった黄。' },
  { id: '27', name: 'キャメル', nameEn: 'Camel', munsell: '7.5YR 6/6', hex: '#C29255', description: 'ラクダの毛のような、黄みがかった明るい茶色。' },
  { id: '28', name: 'ひわだいろ (檜皮色)', nameEn: 'Bark Brown', munsell: '5YR 3/2', hex: '#67443E', description: 'ヒノキの樹皮のような、黒ずんだ茶色。' },
  { id: '29', name: 'ゴールド', nameEn: 'Gold', munsell: '5Y 7/9', hex: '#DAB840', description: '金属の金のような、光沢のあるあざやかな黄。' },
  { id: '30', name: 'カーキ', nameEn: 'Khaki', munsell: '10YR 5/4', hex: '#9C8A4E', description: '軍服にも使われた、土のような黄みの茶色。' },
  { id: '31', name: 'こがねいろ (黄金色)', nameEn: 'Golden Yellow', munsell: '7.5Y 7/12', hex: '#F7B500', description: '山吹色と同義。光り輝く金のような色。' },
  { id: '32', name: 'やまぶきいろ (山吹色)', nameEn: 'Golden Yellow', munsell: '7.5Y 7/12', hex: '#F7B500', description: '山吹の花のような、あざやかな黄。' },
  // 黄系
  { id: '33', name: 'きいろ (黄)', nameEn: 'Yellow', munsell: '5Y 8.5/12', hex: '#FFEE00', description: '最も明度が高い色の一つ。光を象徴する色。' },
  { id: '34', name: 'レモンイエロー', nameEn: 'Lemon Yellow', munsell: '2.5Y 8.5/12', hex: '#FFF300', description: 'レモンの皮のような、澄んだあざやかな黄。' },
  { id: '35', name: 'カナリーイエロー', nameEn: 'Canary Yellow', munsell: '5Y 8/12', hex: '#FFEB38', description: 'カナリアの羽のような、鮮やかな黄。' },
  { id: '36', name: 'クロムイエロー', nameEn: 'Chrome Yellow', munsell: '7.5Y 8/12', hex: '#FFD900', description: '顔料のクロム酸鉛のような、強い黄。' },
  { id: '37', name: 'ゴールデンイエロー', nameEn: 'Golden Yellow', munsell: '7.5Y 7/12', hex: '#F7B500', description: '山吹色と同義。' },
  { id: '38', name: 'マスタード', nameEn: 'Mustard', munsell: '2.5Y 5/6', hex: '#A07E2F', description: '和がらしのような、くすんだ黄。' },
  { id: '39', name: 'アンバー', nameEn: 'Amber', munsell: '10YR 5/8', hex: '#CC9900', description: '琥珀のような、茶色がかった黄。' },
  { id: '40', name: 'オーカー', nameEn: 'Ochre', munsell: '7.5Y 6/8', hex: '#D6AD49', description: '粘土質の天然土から採れる黄土色。' },
  // 黄緑系
  { id: '41', name: 'きみどり (黄緑)', nameEn: 'Yellow Green', munsell: '5GY 7/10', hex: '#A5D100', description: '黄と緑の中間の色。新芽のようなフレッシュな色。' },
  { id: '42', name: 'ライムグリーン', nameEn: 'Lime Green', munsell: '7.5GY 8/10', hex: '#C4E400', description: 'ライムの皮のような、明るく強い黄緑。' },
  { id: '43', name: 'リーフグリーン', nameEn: 'Leaf Green', munsell: '5GY 6/8', hex: '#6EB62C', description: '葉の色のような、中程度の黄緑。' },
  { id: '44', name: 'ウグイス (鶯色)', nameEn: 'Olive Green', munsell: '10Y 4/4', hex: '#6B5B3E', description: 'ウグイスの羽のような、くすんだ黄緑。' },
  { id: '45', name: 'オリーブ', nameEn: 'Olive', munsell: '7.5Y 4/4', hex: '#787439', description: 'オリーブの実のような、くすんだ暗い黄緑。' },
  { id: '46', name: 'モスグリーン', nameEn: 'Moss Green', munsell: '5GY 4/4', hex: '#5F7547', description: '苔（モス）のような、暗くくすんだ緑。' },
  { id: '47', name: 'グラスグリーン', nameEn: 'Grass Green', munsell: '10GY 5/8', hex: '#6AA84F', description: '草のような、明るい黄緑。' },
  // 緑系
  { id: '48', name: 'みどり (緑)', nameEn: 'Green', munsell: '5G 5/8', hex: '#00A651', description: '自然や安らぎを連想させる、基本的な緑。' },
  { id: '49', name: 'エメラルドグリーン', nameEn: 'Emerald Green', munsell: '5G 5/10', hex: '#00A96B', description: '宝石のエメラルドのような、深く鮮やかな緑。' },
  { id: '50', name: 'ビリジアン', nameEn: 'Viridian', munsell: '10G 4/6', hex: '#008761', description: '顔料の緑青のような、青みの強い緑。' },
  { id: '51', name: 'フォレストグリーン', nameEn: 'Forest Green', munsell: '7.5G 3/4', hex: '#2D5A46', description: '深い森のような、暗く落ち着いた緑。' },
  { id: '52', name: '松葉色 (まつばいろ)', nameEn: 'Pine Green', munsell: '2.5G 3/4', hex: '#3A5335', description: '松の葉のような、暗く渋い緑。' },
  { id: '53', name: 'サックスグリーン', nameEn: 'Saxe Green', munsell: '5GY 6/6', hex: '#A0C696', description: 'ドイツのサクソン地方に由来する、くすんだ緑。' },
  { id: '54', name: 'オリーブグリーン', nameEn: 'Olive Green', munsell: '7.5Y 4/4', hex: '#787439', description: 'オリーブのような、暗い黄緑。' },
  { id: '55', name: 'アップルグリーン', nameEn: 'Apple Green', munsell: '5GY 7/8', hex: '#A0D468', description: 'りんごのような、さわやかな黄緑。' },
  { id: '56', name: 'ミントグリーン', nameEn: 'Mint Green', munsell: '5G 8/4', hex: '#C8F2C2', description: 'ハッカ（ミント）のような、淡く明るい緑。' },
  // 青緑系
  { id: '57', name: 'あおみどり (青緑)', nameEn: 'Blue Green', munsell: '2.5BG 5/6', hex: '#009999', description: '緑と青の中間の色。深海のような色。' },
  { id: '58', name: 'ターコイズブルー', nameEn: 'Turquoise Blue', munsell: '5BG 6/8', hex: '#00BABA', description: 'トルコ石のような、明るい緑みの青。' },
  { id: '59', name: 'アクア', nameEn: 'Aqua', munsell: '7.5BG 7/6', hex: '#88D0ED', description: '水（アクア）のような、澄んだ明るい青緑。' },
  { id: '60', name: 'シアン', nameEn: 'Cyan', munsell: '5B 6.5/8', hex: '#00B7EE', description: '印刷の三原色の一つ。鮮やかな緑みの青。' },
  { id: '61', name: 'ピーコックグリーン', nameEn: 'Peacock Green', munsell: '7.5G 4/8', hex: '#00A093', description: '孔雀の羽のような、鮮やかな青緑。' },
  { id: '62', name: 'ティールブルー', nameEn: 'Teal Blue', munsell: '5BG 4/6', hex: '#007F7F', description: '鴨の羽のような、暗い青緑。' },
  { id: '63', name: 'マリンブルー', nameEn: 'Marine Blue', munsell: '7.5B 4/8', hex: '#0077B2', description: '海のような、濃くあざやかな青。' },
  { id: '64', name: 'ナイルブルー', nameEn: 'Nile Blue', munsell: '7.5B 6/6', hex: '#6A9FBC', description: 'ナイル川のような、明るい青。' },
  // 青系
  { id: '65', name: 'あお (青)', nameEn: 'Blue', munsell: '5B 4.5/8', hex: '#0068B7', description: '寒色を代表する、最も彩度の高い青。' },
  { id: '66', name: 'セルリアンブルー', nameEn: 'Cerulean Blue', munsell: '10B 5/8', hex: '#0087CD', description: '澄んだ空のような、明るい青。' },
  { id: '67', name: 'ロイヤルブルー', nameEn: 'Royal Blue', munsell: '2.5PB 3/10', hex: '#0040E3', description: '王室の威厳を表す、濃く鮮やかな青。' },
  { id: '68', name: 'コバルトブルー', nameEn: 'Cobalt Blue', munsell: '7.5B 4/10', hex: '#0067C5', description: '顔料のコバルトのような、あざやかな青。' },
  { id: '69', name: 'ウルトラマリン', nameEn: 'Ultramarine', munsell: '5PB 3/10', hex: '#2243B5', description: '瑠璃（ラピスラズリ）のような、濃い青紫。' },
  { id: '70', name: 'ぐんじょう (群青)', nameEn: 'Ultramarine', munsell: '5PB 3/10', hex: '#2243B5', description: 'ウルトラマリンと同義。' },
  { id: '71', name: 'プルシアンブルー', nameEn: 'Prussian Blue', munsell: '5PB 2/6', hex: '#003366', description: '鉄の化合物からなる顔料。濃い青。' },
  { id: '72', name: 'インディゴ', nameEn: 'Indigo', munsell: '7.5PB 2/4', hex: '#243B60', description: '藍染めの色。深く暗い青。' },
  { id: '73', name: 'ネイビーブルー', nameEn: 'Navy Blue', munsell: '5PB 2/2', hex: '#000040', description: '英国海軍の制服の色のような、濃紺。' },
  { id: '74', name: 'ミッドナイトブルー', nameEn: 'Midnight Blue', munsell: '7.5PB 2/2', hex: '#191970', description: '真夜中の空のような、限りなく黒に近い濃い青。' },
  { id: '75', name: 'そらいろ (空色)', nameEn: 'Sky Blue', munsell: '5B 7/6', hex: '#88D0ED', description: '晴れた日の空のような、明るい青。' },
  { id: '76', name: 'スカイブルー', nameEn: 'Sky Blue', munsell: '5B 7/6', hex: '#88D0ED', description: '空色と同義。' },
  { id: '77', name: 'ベビーブルー', nameEn: 'Baby Blue', munsell: '7.5B 8/4', hex: '#C8E4F8', description: '赤ちゃんの産着のような、ごく淡い青。' },
  // 青紫系
  { id: '78', name: 'あおむらさき (青紫)', nameEn: 'Violet Blue', munsell: '10PB 4/10', hex: '#5B0099', description: '青みが強い紫。冷静な印象。' },
  { id: '79', name: 'すみれいろ (菫色)', nameEn: 'Violet', munsell: '5P 4/10', hex: '#930099', description: 'スミレの花のような、青みがかった紫。' },
  { id: '80', name: 'ふじいろ (藤色)', nameEn: 'Wisteria', munsell: '7.5PB 7/4', hex: '#A8A8D0', description: '藤の花のような、淡く優しい青紫。' },
  { id: '81', name: 'ラベンダー', nameEn: 'Lavender', munsell: '5P 7/4', hex: '#B5B5E1', description: 'ラベンダーの花のような、明るく淡い紫。' },
  { id: '82', name: 'アイリス', nameEn: 'Iris', munsell: '10PB 5/8', hex: '#6A5ACD', description: 'アヤメ科のアイリスの花のような、青紫。' },
  { id: '83', name: 'ライラック', nameEn: 'Lilac', munsell: '10P 7/6', hex: '#D0B7D5', description: 'ライラックの花のような、明るい紫。' },
  // 紫系
  { id: '84', name: 'むらさき (紫)', nameEn: 'Violet', munsell: '5P 4/10', hex: '#930099', description: '赤と青の中間の色。高貴、神秘的な色。' },
  { id: '85', name: 'パープル', nameEn: 'Purple', munsell: '5P 4/10', hex: '#930099', description: '紫と同義。' },
  { id: '86', name: 'アメジスト', nameEn: 'Amethyst', munsell: '5P 5/8', hex: '#9966CC', description: '宝石のアメシスト（紫水晶）のような、紫。' },
  { id: '87', name: 'ぶどういろ (葡萄色)', nameEn: 'Grape', munsell: '2.5P 3/6', hex: '#6A2E5B', description: 'ブドウのような、濃い紫。' },
  { id: '88', name: 'しそいろ (紫蘇色)', nameEn: 'Perilla', munsell: '10P 3/4', hex: '#663366', description: 'シソの葉のような、暗くくすんだ赤紫。' },
  { id: '89', name: 'バイオレット', nameEn: 'Violet', munsell: '5P 4/10', hex: '#930099', description: '紫と同義。' },
  // 赤紫系
  { id: '90', name: 'あかむらさき (赤紫)', nameEn: 'Red Violet', munsell: '7.5RP 4/12', hex: '#C80096', description: '赤みが強い紫。華やかな印象。' },
  { id: '91', name: 'モーヴ', nameEn: 'Mauve', munsell: '5RP 5/6', hex: '#993366', description: 'アニリン染料から生まれた、くすんだ赤紫。' },
  { id: '92', name: 'つつじいろ (躑躅色)', nameEn: 'Azalea', munsell: '7.5RP 5/12', hex: '#DE008C', description: 'ツツジの花のような、あざやかな赤紫。' },
  { id: '93', name: 'えびいろ (葡萄色)', nameEn: 'Wine', munsell: '10RP 3/4', hex: '#6B3F56', description: '濃いブドウのような、暗い赤紫。' },
  { id: '94', name: 'うめぞめ (梅染)', nameEn: 'Plum', munsell: '10R 5/6', hex: '#A53B3B', description: '梅の樹皮で染めた、くすんだ赤。' },
  { id: '95', name: 'うすべにいろ (薄紅)', nameEn: 'Pale Rose', munsell: '5RP 8/4', hex: '#F0C0C8', description: '淡く薄い赤紫。' },
  // 茶系・アースカラー
  { id: '96', name: 'ちゃいろ (茶色)', nameEn: 'Brown', munsell: '10YR 3/4', hex: '#804000', description: '土や木のような、一般的な茶色。' },
  { id: '97', name: 'こげちゃ (焦茶)', nameEn: 'Dark Brown', munsell: '10YR 2/2', hex: '#4D2600', description: '非常に暗い、黒に近い茶色。' },
  { id: '98', name: 'セピア', nameEn: 'Sepia', munsell: '5YR 3/2', hex: '#5D473A', description: 'イカ墨由来の顔料。暗い赤みの茶色。' },
  { id: '99', name: 'マロン', nameEn: 'Maroon', munsell: '5R 3/2', hex: '#5D323A', description: '栗のような、暗い赤みの茶色。' },
  { id: '100', name: '栗色 (くりいろ)', nameEn: 'Chestnut', munsell: '7.5YR 4/4', hex: '#8C5A4C', description: '栗の実のような、赤みがかった茶色。' },
  { id: '101', name: 'トースト', nameEn: 'Toast', munsell: '10YR 6/4', hex: '#B3885C', description: '焼いたパンのような、黄みの茶色。' },
  { id: '102', name: 'ベージュ', nameEn: 'Beige', munsell: '7.5Y 8/2', hex: '#C8AD7F', description: '砂や羊毛のような、ごく薄い黄みの茶色。' },
  { id: '103', name: 'クリーム', nameEn: 'Cream', munsell: '2.5Y 8.5/4', hex: '#FFEEA0', description: '生クリームのような、ごく薄い黄。' },
  { id: '104', name: 'バニラ', nameEn: 'Vanilla', munsell: '5Y 9/2', hex: '#FFF3D9', description: 'バニラのような、極めて淡い黄。' },
  { id: '105', name: 'オイスターホワイト', nameEn: 'Oyster White', munsell: '10Y 9/1', hex: '#F2F2E6', description: '牡蠣の殻のような、ごくわずかに黄みのある白。' },
  { id: '106', name: 'ライトオーカー', nameEn: 'Light Ochre', munsell: '7.5Y 7/6', hex: '#D9C587', description: '明るい黄土色。' },
  { id: '107', name: 'サンド', nameEn: 'Sand', munsell: '10YR 7/4', hex: '#D4C09A', description: '砂のような、明るい黄みの茶色。' },
  { id: '108', name: 'ダンディライオン', nameEn: 'Dandelion', munsell: '5Y 8/10', hex: '#FFD200', description: 'タンポポの花のような、あざやかな黄。' },
  // グレイッシュカラー
  { id: '109', name: 'オールドローズ', nameEn: 'Old Rose', munsell: '5R 5/4', hex: '#99505B', description: '古いバラのような、くすんだ赤。' },
  { id: '110', name: 'ダスティローズ', nameEn: 'Dusty Rose', munsell: '7.5RP 6/4', hex: '#C899AE', description: 'ほこりっぽいバラのような、くすんだ赤紫。' },
  { id: '111', name: 'ラセット', nameEn: 'Russet', munsell: '5R 4/6', hex: '#A8493D', description: '赤茶けた、くすんだ赤。' },
  { id: '112', name: 'レンガ色 (れんがいろ)', nameEn: 'Brick Red', munsell: '5R 4/4', hex: '#8C4949', description: '焼きレンガのような、くすんだ赤。' },
  { id: '113', name: 'マルーン', nameEn: 'Maroon', munsell: '7.5R 3/4', hex: '#7F3F4C', description: '栗のような、暗い赤。' },
  { id: '114', name: 'カーキグリーン', nameEn: 'Khaki Green', munsell: '5GY 5/4', hex: '#868B5E', description: '軍服に使われる、くすんだ緑。' },
  { id: '115', name: 'サビ色 (さびいろ)', nameEn: 'Rust', munsell: '5YR 4/4', hex: '#8B4513', description: '鉄の錆のような、くすんだ黄赤。' },
  { id: '116', name: 'ブルーグレー', nameEn: 'Blue Gray', munsell: '5B 5/2', hex: '#608D9A', description: '青みがかった灰色。' },
  { id: '117', name: 'グリーンティー', nameEn: 'Green Tea', munsell: '7.5GY 6/4', hex: '#99AD7A', description: '緑茶のような、くすんだ黄緑。' },
  { id: '118', name: 'スモーク', nameEn: 'Smoke', munsell: '7.5PB 6/2', hex: '#99AABB', description: '煙のような、くすんだ青紫。' },
  { id: '119', name: 'モーブ', nameEn: 'Mauve', munsell: '5RP 5/6', hex: '#993366', description: 'くすんだ赤紫。' },
  { id: '120', name: 'くちばいろ (朽葉色)', nameEn: 'Decayed Leaf', munsell: '10YR 5/4', hex: '#9C8A4E', description: '朽ちた葉のような、くすんだ茶色。' },
  // 無彩色系
  { id: '121', name: 'しろ (白)', nameEn: 'White', munsell: 'N 9.5', hex: '#FFFFFF', description: '最も明度の高い無彩色。' },
  { id: '122', name: 'オフホワイト', nameEn: 'Off White', munsell: 'N 9', hex: '#F2F2F2', description: 'ごくわずかに色みや濁りのある白。' },
  { id: '123', name: 'アイボリー', nameEn: 'Ivory', munsell: '7.5Y 8.5/2', hex: '#F8F4E8', description: '象牙のような、ごく淡い黄。' },
  { id: '124', name: '灰色 (はいいろ)', nameEn: 'Gray', munsell: 'N 5', hex: '#808080', description: '白と黒の中間の無彩色。' },
  { id: '125', name: 'ライトグレー', nameEn: 'Light Gray', munsell: 'N 7.5', hex: '#C0C0C0', description: '明るい灰色。' },
  { id: '126', name: 'ダークグレー', nameEn: 'Dark Gray', munsell: 'N 3', hex: '#4D4D4D', description: '暗い灰色。' },
  { id: '127', name: 'くろ (黒)', nameEn: 'Black', munsell: 'N 1', hex: '#000000', description: '最も明度の低い無彩色。' },
];