export const INITIAL_TIME = 30; // seconds
export const PENALTY_SECONDS = 3;
export const CHOICE_COUNT = 2;
export const GOLD_STRAWBERRY_CHANCE = 0.03; // 3% chance for cake (about 1 in 33)
export const GOLD_STRAWBERRY_POINTS = 3;
export const GOLD_STRAWBERRY_TIME_BONUS = 10; // 1 second in 0.1 second units
export const WHOLE_CAKE_CHANCE = 0.01; // 1% chance for whole cake (about 1 in 100)
export const WHOLE_CAKE_POINTS = 5;
export const WHOLE_CAKE_TIME_BONUS = 50; // 5 seconds in 0.1 second units
export const MEMORY_GAME_CHANCE = 1.0; // 100% chance for memory game
export const DISTRACTOR_EMOJIS = ['🍎', '🍊', '🍇', '🍉', '🍍', '🍑', '🥝', '🫐', '🍒', '🍈'];

// Island game constants
export const ISLAND_NAMES = [
  { id: 'aogashima', name: '青ヶ島', file: 'aogashima.svg' },
  { id: 'hachijojima', name: '八丈島', file: 'hachijojima.svg' },
  { id: 'hachijokojima', name: '八丈小島', file: 'hachijokojima.svg' },
  { id: 'hatsushima', name: '初島', file: 'hatsushima.svg' },
  { id: 'kozushima', name: '神津島', file: 'kozushima.svg' },
  { id: 'miyakejima', name: '三宅島', file: 'miyakejima.svg' },
  { id: 'oshima', name: '大島', file: 'oshima.svg' }
];

// Flag game constants
export const COUNTRIES = [
  // アジア
  { id: 'japan', name: '日本', code: 'jp' },
  { id: 'china', name: '中国', code: 'cn' },
  { id: 'korea', name: '韓国', code: 'kr' },
  { id: 'thailand', name: 'タイ', code: 'th' },
  { id: 'singapore', name: 'シンガポール', code: 'sg' },
  { id: 'malaysia', name: 'マレーシア', code: 'my' },
  { id: 'indonesia', name: 'インドネシア', code: 'id' },
  { id: 'philippines', name: 'フィリピン', code: 'ph' },
  { id: 'vietnam', name: 'ベトナム', code: 'vn' },
  { id: 'india', name: 'インド', code: 'in' },
  { id: 'pakistan', name: 'パキスタン', code: 'pk' },
  { id: 'bangladesh', name: 'バングラデシュ', code: 'bd' },
  { id: 'sri-lanka', name: 'スリランカ', code: 'lk' },
  { id: 'myanmar', name: 'ミャンマー', code: 'mm' },
  { id: 'cambodia', name: 'カンボジア', code: 'kh' },
  { id: 'laos', name: 'ラオス', code: 'la' },
  { id: 'brunei', name: 'ブルネイ', code: 'bn' },
  { id: 'mongolia', name: 'モンゴル', code: 'mn' },
  { id: 'north-korea', name: '北朝鮮', code: 'kp' },
  { id: 'taiwan', name: '台湾', code: 'tw' },
  { id: 'hong-kong', name: '香港', code: 'hk' },
  { id: 'macau', name: 'マカオ', code: 'mo' },
  { id: 'nepal', name: 'ネパール', code: 'np' },
  { id: 'bhutan', name: 'ブータン', code: 'bt' },
  { id: 'maldives', name: 'モルディブ', code: 'mv' },
  { id: 'afghanistan', name: 'アフガニスタン', code: 'af' },
  { id: 'uzbekistan', name: 'ウズベキスタン', code: 'uz' },
  { id: 'kazakhstan', name: 'カザフスタン', code: 'kz' },
  { id: 'kyrgyzstan', name: 'キルギス', code: 'kg' },
  { id: 'tajikistan', name: 'タジキスタン', code: 'tj' },
  { id: 'turkmenistan', name: 'トルクメニスタン', code: 'tm' },
  
  // ヨーロッパ
  { id: 'uk', name: 'イギリス', code: 'gb' },
  { id: 'france', name: 'フランス', code: 'fr' },
  { id: 'germany', name: 'ドイツ', code: 'de' },
  { id: 'italy', name: 'イタリア', code: 'it' },
  { id: 'spain', name: 'スペイン', code: 'es' },
  { id: 'netherlands', name: 'オランダ', code: 'nl' },
  { id: 'belgium', name: 'ベルギー', code: 'be' },
  { id: 'switzerland', name: 'スイス', code: 'ch' },
  { id: 'austria', name: 'オーストリア', code: 'at' },
  { id: 'sweden', name: 'スウェーデン', code: 'se' },
  { id: 'norway', name: 'ノルウェー', code: 'no' },
  { id: 'denmark', name: 'デンマーク', code: 'dk' },
  { id: 'finland', name: 'フィンランド', code: 'fi' },
  { id: 'iceland', name: 'アイスランド', code: 'is' },
  { id: 'ireland', name: 'アイルランド', code: 'ie' },
  { id: 'portugal', name: 'ポルトガル', code: 'pt' },
  { id: 'greece', name: 'ギリシャ', code: 'gr' },
  { id: 'poland', name: 'ポーランド', code: 'pl' },
  { id: 'czech', name: 'チェコ', code: 'cz' },
  { id: 'slovakia', name: 'スロバキア', code: 'sk' },
  { id: 'hungary', name: 'ハンガリー', code: 'hu' },
  { id: 'romania', name: 'ルーマニア', code: 'ro' },
  { id: 'bulgaria', name: 'ブルガリア', code: 'bg' },
  { id: 'croatia', name: 'クロアチア', code: 'hr' },
  { id: 'serbia', name: 'セルビア', code: 'rs' },
  { id: 'bosnia', name: 'ボスニア・ヘルツェゴビナ', code: 'ba' },
  { id: 'montenegro', name: 'モンテネグロ', code: 'me' },
  { id: 'albania', name: 'アルバニア', code: 'al' },
  { id: 'north-macedonia', name: '北マケドニア', code: 'mk' },
  { id: 'slovenia', name: 'スロベニア', code: 'si' },
  { id: 'estonia', name: 'エストニア', code: 'ee' },
  { id: 'latvia', name: 'ラトビア', code: 'lv' },
  { id: 'lithuania', name: 'リトアニア', code: 'lt' },
  { id: 'belarus', name: 'ベラルーシ', code: 'by' },
  { id: 'ukraine', name: 'ウクライナ', code: 'ua' },
  { id: 'moldova', name: 'モルドバ', code: 'md' },
  { id: 'russia', name: 'ロシア', code: 'ru' },
  { id: 'georgia', name: 'ジョージア', code: 'ge' },
  { id: 'armenia', name: 'アルメニア', code: 'am' },
  { id: 'azerbaijan', name: 'アゼルバイジャン', code: 'az' },
  { id: 'turkey', name: 'トルコ', code: 'tr' },
  { id: 'cyprus', name: 'キプロス', code: 'cy' },
  { id: 'malta', name: 'マルタ', code: 'mt' },
  { id: 'luxembourg', name: 'ルクセンブルク', code: 'lu' },
  { id: 'monaco', name: 'モナコ', code: 'mc' },
  { id: 'andorra', name: 'アンドラ', code: 'ad' },
  { id: 'san-marino', name: 'サンマリノ', code: 'sm' },
  { id: 'vatican', name: 'バチカン', code: 'va' },
  { id: 'liechtenstein', name: 'リヒテンシュタイン', code: 'li' },
  
  // 北アメリカ
  { id: 'usa', name: 'アメリカ', code: 'us' },
  { id: 'canada', name: 'カナダ', code: 'ca' },
  { id: 'mexico', name: 'メキシコ', code: 'mx' },
  { id: 'guatemala', name: 'グアテマラ', code: 'gt' },
  { id: 'belize', name: 'ベリーズ', code: 'bz' },
  { id: 'el-salvador', name: 'エルサルバドル', code: 'sv' },
  { id: 'honduras', name: 'ホンジュラス', code: 'hn' },
  { id: 'nicaragua', name: 'ニカラグア', code: 'ni' },
  { id: 'costa-rica', name: 'コスタリカ', code: 'cr' },
  { id: 'panama', name: 'パナマ', code: 'pa' },
  { id: 'cuba', name: 'キューバ', code: 'cu' },
  { id: 'jamaica', name: 'ジャマイカ', code: 'jm' },
  { id: 'haiti', name: 'ハイチ', code: 'ht' },
  { id: 'dominican-republic', name: 'ドミニカ共和国', code: 'do' },
  { id: 'bahamas', name: 'バハマ', code: 'bs' },
  { id: 'barbados', name: 'バルバドス', code: 'bb' },
  { id: 'trinidad-tobago', name: 'トリニダード・トバゴ', code: 'tt' },
  
  // 南アメリカ
  { id: 'brazil', name: 'ブラジル', code: 'br' },
  { id: 'argentina', name: 'アルゼンチン', code: 'ar' },
  { id: 'chile', name: 'チリ', code: 'cl' },
  { id: 'peru', name: 'ペルー', code: 'pe' },
  { id: 'colombia', name: 'コロンビア', code: 'co' },
  { id: 'venezuela', name: 'ベネズエラ', code: 've' },
  { id: 'ecuador', name: 'エクアドル', code: 'ec' },
  { id: 'bolivia', name: 'ボリビア', code: 'bo' },
  { id: 'paraguay', name: 'パラグアイ', code: 'py' },
  { id: 'uruguay', name: 'ウルグアイ', code: 'uy' },
  { id: 'guyana', name: 'ガイアナ', code: 'gy' },
  { id: 'suriname', name: 'スリナム', code: 'sr' },
  
  // アフリカ
  { id: 'south-africa', name: '南アフリカ', code: 'za' },
  { id: 'egypt', name: 'エジプト', code: 'eg' },
  { id: 'nigeria', name: 'ナイジェリア', code: 'ng' },
  { id: 'kenya', name: 'ケニア', code: 'ke' },
  { id: 'ethiopia', name: 'エチオピア', code: 'et' },
  { id: 'ghana', name: 'ガーナ', code: 'gh' },
  { id: 'morocco', name: 'モロッコ', code: 'ma' },
  { id: 'algeria', name: 'アルジェリア', code: 'dz' },
  { id: 'tunisia', name: 'チュニジア', code: 'tn' },
  { id: 'libya', name: 'リビア', code: 'ly' },
  { id: 'sudan', name: 'スーダン', code: 'sd' },
  { id: 'uganda', name: 'ウガンダ', code: 'ug' },
  { id: 'tanzania', name: 'タンザニア', code: 'tz' },
  { id: 'zambia', name: 'ザンビア', code: 'zm' },
  { id: 'zimbabwe', name: 'ジンバブエ', code: 'zw' },
  { id: 'botswana', name: 'ボツワナ', code: 'bw' },
  { id: 'namibia', name: 'ナミビア', code: 'na' },
  { id: 'angola', name: 'アンゴラ', code: 'ao' },
  { id: 'mozambique', name: 'モザンビーク', code: 'mz' },
  { id: 'madagascar', name: 'マダガスカル', code: 'mg' },
  { id: 'mauritius', name: 'モーリシャス', code: 'mu' },
  { id: 'senegal', name: 'セネガル', code: 'sn' },
  { id: 'ivory-coast', name: 'コートジボワール', code: 'ci' },
  { id: 'mali', name: 'マリ', code: 'ml' },
  { id: 'burkina-faso', name: 'ブルキナファソ', code: 'bf' },
  { id: 'niger', name: 'ニジェール', code: 'ne' },
  { id: 'chad', name: 'チャド', code: 'td' },
  { id: 'cameroon', name: 'カメルーン', code: 'cm' },
  { id: 'gabon', name: 'ガボン', code: 'ga' },
  { id: 'congo', name: 'コンゴ共和国', code: 'cg' },
  { id: 'drc', name: 'コンゴ民主共和国', code: 'cd' },
  { id: 'rwanda', name: 'ルワンダ', code: 'rw' },
  { id: 'burundi', name: 'ブルンジ', code: 'bi' },
  
  // オセアニア
  { id: 'australia', name: 'オーストラリア', code: 'au' },
  { id: 'new-zealand', name: 'ニュージーランド', code: 'nz' },
  { id: 'fiji', name: 'フィジー', code: 'fj' },
  { id: 'papua-new-guinea', name: 'パプアニューギニア', code: 'pg' },
  { id: 'samoa', name: 'サモア', code: 'ws' },
  { id: 'tonga', name: 'トンガ', code: 'to' },
  { id: 'vanuatu', name: 'バヌアツ', code: 'vu' },
  { id: 'solomon-islands', name: 'ソロモン諸島', code: 'sb' },
  { id: 'palau', name: 'パラオ', code: 'pw' },
  { id: 'micronesia', name: 'ミクロネシア', code: 'fm' },
  { id: 'marshall-islands', name: 'マーシャル諸島', code: 'mh' },
  { id: 'kiribati', name: 'キリバス', code: 'ki' },
  { id: 'tuvalu', name: 'ツバル', code: 'tv' },
  { id: 'nauru', name: 'ナウル', code: 'nr' },
  
  // 中東
  { id: 'saudi-arabia', name: 'サウジアラビア', code: 'sa' },
  { id: 'uae', name: 'アラブ首長国連邦', code: 'ae' },
  { id: 'qatar', name: 'カタール', code: 'qa' },
  { id: 'kuwait', name: 'クウェート', code: 'kw' },
  { id: 'bahrain', name: 'バーレーン', code: 'bh' },
  { id: 'oman', name: 'オマーン', code: 'om' },
  { id: 'yemen', name: 'イエメン', code: 'ye' },
  { id: 'iraq', name: 'イラク', code: 'iq' },
  { id: 'iran', name: 'イラン', code: 'ir' },
  { id: 'syria', name: 'シリア', code: 'sy' },
  { id: 'lebanon', name: 'レバノン', code: 'lb' },
  { id: 'jordan', name: 'ヨルダン', code: 'jo' },
  { id: 'israel', name: 'イスラエル', code: 'il' },
  { id: 'palestine', name: 'パレスチナ', code: 'ps' }
];